In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [2]:
dataset = pd.read_csv("boston2.csv",header=None)

In [3]:
dataset.shape

(506, 105)

In [4]:
dataset.head()

0     1         2    3         4         5         6         7    \
0  0.000000  0.18  0.067815  0.0  0.314815  0.577505  0.641607  0.269203   
1  0.000236  0.00  0.242302  0.0  0.172840  0.547998  0.782698  0.348962   
2  0.000236  0.00  0.242302  0.0  0.172840  0.694386  0.599382  0.348962   
3  0.000293  0.00  0.063050  0.0  0.150206  0.658555  0.441813  0.448545   
4  0.000705  0.00  0.063050  0.0  0.150206  0.687105  0.528321  0.448545   

        8         9    ...       95        96        97        98        99   \
0  0.000000  0.208015  ...  0.059749  0.208015  0.018655  0.082503  0.287234   
1  0.043478  0.104962  ...  0.058064  0.104962  0.021462  0.306021  0.553191   
2  0.043478  0.104962  ...  0.058064  0.103885  0.006661  0.306021  0.547514   
3  0.086957  0.066794  ...  0.043345  0.066412  0.002230  0.421118  0.645222   
4  0.086957  0.066794  ...  0.043345  0.066794  0.006635  0.421118  0.648936   

        100       101       102       103   104  
0  0.025759  1.000000  0.089680  0.008042  24.0  
1  0.113111  1.000000  0.204470  0.041808  21.6  
2  0.035109  0.979580  0.062814  0.004028  34.7  
3  0.021667  0.988585  0.033197  0.001115  33.4  
4  0.064464  1.000000  0.099338  0.009868  36.2  

[5 rows x 105 columns]

In [5]:
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [6]:
lreg = LinearRegression()
lreg.fit(X_train,Y_train)

LinearRegression()

In [7]:
print("TRAIN SCORE:",lreg.score(X_train,Y_train))
print("TEST SCORE:",lreg.score(X_test,Y_test))

TRAIN SCORE: 0.9520519609032729
TEST SCORE: 0.6074721959665745


In [8]:
lreg.coef_

array([-4.12710947e+02, -5.22432068e+01, -1.31898815e+02, -1.20041365e+01,
       -1.55107129e+01,  2.87163342e+01,  5.47040992e+01, -4.95346659e+01,
        2.65823927e+01,  3.70620316e+01, -1.18281674e+01, -1.80581965e+01,
       -1.95246830e+01,  1.22025403e+01,  2.98078144e+03,  1.50084257e+03,
        1.14187325e+02, -1.69700520e+01,  4.09613691e+01, -2.42636646e+01,
        5.76157466e+01,  1.27812142e+03, -2.23986944e+03,  2.22825472e+02,
       -2.18201083e+00,  4.29960320e+01, -1.33981515e+01, -1.93893485e+01,
       -2.57541277e+00, -8.10130128e+01,  9.66019367e+00,  4.91423718e+00,
       -8.12114800e-01, -7.64694179e+00,  3.37837099e+01, -1.14464390e+01,
        6.85083979e+01, -1.73753604e+01,  4.28128204e+01,  1.13988209e+00,
       -7.72696840e-01,  5.68255921e+01,  1.42875996e+01,  5.39551110e+01,
       -3.21709644e+01,  1.92709675e+01, -1.38852338e+01,  6.06343266e+01,
       -1.23153942e+01, -1.20041365e+01, -1.77243899e+01, -3.39868183e+01,
        7.08999816e+00, -

In [13]:
y_train_pred = lreg.predict(X_train)
y_test_pred = lreg.predict(X_test)
print ("TRAIN mean_absolute_error :",mean_absolute_error(Y_train, y_train_pred))
print ("TEST mean_absolute_error :",mean_absolute_error(Y_test, y_test_pred))
print ("TRAIN root_mean_squared_error : ",np.sqrt(mean_squared_error(Y_train, y_train_pred)))
print ("TEST root_mean_squared_error : ",np.sqrt(mean_squared_error(Y_test, y_test_pred)))
print ("TRAIN R2 score :",r2_score(Y_train, y_train_pred))
print ("TEST R2 score :",r2_score(Y_test, y_test_pred))

TRAIN mean_absolute_error : 1.5674141791450378
TEST mean_absolute_error : 3.2258952120186457
TRAIN root_mean_squared_error :  2.0224644898103343
TEST root_mean_squared_error :  5.662961691693065
TRAIN R2 score : 0.9520519609032729
TEST R2 score : 0.6074721959665745


In [14]:
ridgeR = Ridge(alpha=1)
ridgeR.fit(X_train,Y_train)
print("TRAIN R2 SCORE:",ridgeR.score(X_train,Y_train))
print("TEST R2 SCORE:",ridgeR.score(X_test,Y_test))

TRAIN SCORE: 0.8857966585170943
TEST SCORE: 0.7527683481744762


In [17]:
y_train_pred = ridgeR.predict(X_train)
y_test_pred = ridgeR.predict(X_test)
print ("TRAIN mean_absolute_error :",mean_absolute_error(Y_train, y_train_pred))
print ("TEST mean_absolute_error :",mean_absolute_error(Y_test, y_test_pred))
print ("TRAIN root_mean_squared_error : ",np.sqrt(mean_squared_error(Y_train, y_train_pred)))
print ("TEST root_mean_squared_error : ",np.sqrt(mean_squared_error(Y_test, y_test_pred)))

TRAIN mean_absolute_error : 2.1656396671236773
TEST mean_absolute_error : 2.9626926001410037
TRAIN root_mean_squared_error :  3.1212954928560985
TEST root_mean_squared_error :  4.494283317645133


In [18]:
ridgeR.coef_

array([-1.41368408e+00, -1.55661895e+00, -1.46543409e+00, -1.26616071e-01,
       -7.91193605e-02,  8.33161023e+00,  2.54975060e-01, -4.94145701e+00,
        3.89862268e+00, -1.05866058e+00, -1.58433734e+00,  1.05103856e+00,
       -4.01220799e+00,  3.33720475e-01,  3.64725471e-03, -8.49295793e-01,
        7.44989267e-01, -1.43106836e+00, -1.62981017e+00, -1.40486294e+00,
       -4.47314366e-02, -1.74619880e+00, -1.46715888e+00, -1.33237111e+00,
       -1.69154625e+00, -5.06179637e-01,  2.62197591e+00, -2.09210002e+00,
        1.95074661e-01, -2.75469422e-01,  5.11308202e+00, -1.67083739e+00,
       -9.81863179e-02,  6.34477127e-01, -6.10008281e-01,  4.01805897e-02,
       -1.27661999e+00, -2.91349679e+00,  3.39544035e+00,  7.91904036e-01,
        1.35260232e+00, -4.03661265e+00,  2.32361734e+00, -3.36712926e+00,
        1.81279204e+00,  3.01566897e+00, -1.89452070e+00, -2.50844073e-01,
       -2.89543735e+00, -1.26616071e-01, -5.00217192e+00, -2.43951806e+00,
        2.85071846e+00, -

In [19]:
lassoR = Lasso(alpha=1)
lassoR.fit(X_train,Y_train)
print("TRAIN SCORE:",lassoR.score(X_train,Y_train))
print("TEST SCORE:",lassoR.score(X_test,Y_test))

TRAIN SCORE: 0.29323768991114596
TEST SCORE: 0.20937503255272272


In [ ]:
lassoR.coef_

array([ -0.        ,   0.        ,  -0.        ,   0.        ,
        -0.        ,   0.        ,  -0.        ,   0.        ,
        -0.        ,  -1.08752637,  -0.        ,   0.        ,
       -10.47130775,  -0.        ,   0.        ,  -0.        ,
         0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,  -0.        ,   0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.        ,
        -0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,  -0.        ,
        -0.        ,  -0.        ,  -0.        ,  -0.  

In [20]:
y_train_pred = lassoR.predict(X_train)
y_test_pred = lassoR.predict(X_test)
print ("TRAIN mean_absolute_error :",mean_absolute_error(Y_train, y_train_pred))
print ("TEST mean_absolute_error :",mean_absolute_error(Y_test, y_test_pred))
print ("TRAIN root_mean_squared_error : ",np.sqrt(mean_squared_error(Y_train, y_train_pred)))
print ("TEST root_mean_squared_error : ",np.sqrt(mean_squared_error(Y_test, y_test_pred)))

TRAIN mean_absolute_error : 5.512753169106904
TEST mean_absolute_error : 5.488898627760889
TRAIN root_mean_squared_error :  7.764833907685628
TEST root_mean_squared_error :  8.036994551520348
